### ISSUE TITLE
Result using Kitti odom data

### ISSUE THREAD

**Issue by wwtinwhu** [hku-mars/BALM#15]
Thanks for your work! I test BALM using Kitti odom data by using a_loam as front-end, and BALM as back-end.  I found that using default parameter the result after BA gets worse in height.  Does anyone have any suggestion or ideas? Below is a part of traj. Purple is gt, red is a_loam, green is aloam+BALM. 
![image](https://user-images.githubusercontent.com/28035224/132302948-1568f06d-b9c3-49e9-98b8-108ab15d8e0d.png)

**Comment by HerB1998** [comment]
> Thanks for your work! I test BALM using Kitti odom data by using a_loam as front-end, and BALM as back-end. I found that using default parameter the result after BA gets worse in height. Does anyone have any suggestion or ideas? Below is a part of traj. Purple is gt, red is a_loam, green is aloam+BALM. ![image](https://user-images.githubusercontent.com/28035224/132302948-1568f06d-b9c3-49e9-98b8-108ab15d8e0d.png)
Hello, did you solve this problem?Could I solve this problem by changing the parameter?
