### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by lijian636** [hku-mars/BALM#2]
When I compile, I have installed the  livox-ros-driver, but the following errors will occur,
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "livox_ros_driver"
  with any of the following names:

    livox_ros_driverConfig.cmake
    livox_ros_driver-config.cmake

**Comment by Saki-Chen** [comment]
Maybe you need to source setup.bash of the driver.

**Comment by Zale-Liu** [comment]
> Maybe you need to source setup.bash of the driver.

Yes. The project relies on a self-defined message of livox_ros_driver. You can complied livox_ros_driver and source the path.

**Comment by Cioler** [comment]
I have the same question,but I cant find livox_ros_driverConfig.cmake or livox_ros_driver-config.cmake in my ubuntu,how can i find them?
