### ISSUE TITLE
edge feature

### ISSUE THREAD

**Issue by wangq0688** [hku-mars/BALM#31]
Dear Author.

Will subsequent versions update the edge feature module?

**Comment by Zale-Liu** [comment]
Since we cannot get accurate edge points, we will not add the edge feature module to the optimizer.

**Comment by wangq0688** [comment]
thanks for your reply，Can I get the corresponding Hesssian and Jacobian matrix by changing the value of kk in function acc_evaluate2 (bavoxel.hpp l53) ?
If kk=1, am I getting the residual of lambda2?

**Comment by Zale-Liu** [comment]
> thanks for your reply，Can I get the corresponding Hesssian and Jacobian matrix by changing the value of kk in function acc_evaluate2 (bavoxel.hpp l53) ? If kk=1, am I getting the residual of lambda2?

Yes, when you set kk=1, you get the residual, Hessian and Jacobian matrix for lambda2.
