### ISSUE TITLE
BALM 1.0 Formula Question?

### ISSUE THREAD

**Issue by qpc001** [hku-mars/BALM#34]
APPENDIX A.

1. How the \bar{p} to 1/N(p_i) ?
2. Why ignore u_k to p_i partial derivative ？

![image](https://user-images.githubusercontent.com/31476516/208303388-b1334146-4581-41c6-8319-56fecf12249f.png)

**Comment by huanglilong** [comment]
@qpc001  check here.
![image](https://user-images.githubusercontent.com/7278867/211271614-9f567d78-bcea-4ab4-8e69-d85c2dce00c4.png)

**Comment by Zale-Liu** [comment]
> @qpc001 check here. ![image](https://user-images.githubusercontent.com/7278867/211271614-9f567d78-bcea-4ab4-8e69-d85c2dce00c4.png)

Yes, the answer is right.

**Comment by qpc001** [comment]
Thanks😄
