### ISSUE TITLE
Performance of outdoor scenes is poor

### ISSUE THREAD

**Issue by zhumenga** [hku-mars/BALM#36]
Thank you for your excellent work，In outdoor scenes, the point cloud is corrected by using the optimized posture, and the point cloud becomes very poor。I tried modifying the following parameters to make the input plane feature as good as possible（eigen_value_array and voxel_size），I don't know where the problem is。

**Comment by Zale-Liu** [comment]
We have tested the algorithms on many outdoor datasets and the results work well. There are some points that you should note:
1. The point clouds you use should be undistorted. (such as the point cloud outputed from FAST-LIO2).
2. The point clouds and poses must be corresponding. You can comment out the BA optimization and just display the point cloud map in RVIZ, to check whether the initial value work well.

**Comment by zhumenga** [comment]
Thanks for your suggestion, I will try it
