### ISSUE TITLE
ubuntu18.04 To support the program installation

### ISSUE THREAD

**Issue by kxch928925819** [hku-mars/BALM#5]
Ubuntu  18.04. ROS  Melodic. 
 PCL 1.8.0
 Eigen 3.3.4
CERES 1.1.4
 openCV3.2

.

**Comment by Zale-Liu** [comment]
I have tested the codes on Ubuntu 18.04 and it can work. What is your problem?

**Comment by kxch928925819** [comment]
Tankyou very much ! I wait FAST-LIO 2.0 ,becuse I had Livox-horizon manifold 2-c ,GPS(reach m2) !
