### ISSUE TITLE
ceres自动导数可以收敛但是解析导数无法收敛

### ISSUE THREAD

**Issue by Torchmm** [hku-mars/BALM#59]
你好，我试图采用ceres solver来进行优化，我实现了ceres的自动导数和解析导数的残差函数，发现ceres在自动导数情况下能够收敛，但是采用代码里的解析导数的代码无法收敛，并且我使用ceres solver的工具GradientChecker进行查看，发现ceres solver的自动导数得到的雅可比和解析导数雅可比相差比较大。
![c9cf6510402f02535877d1e9d6803bc](https://github.com/user-attachments/assets/72873bbf-d1e8-485f-914f-ed179eee34e4)
我分别采用了左扰动模型和右扰动模型，发现都一样无法收敛。麻烦帮我看看是什么原因。我已经确保了解析导数和代码里的一致，结果也一致。

**Comment by neu-yuezhang** [comment]
Hello, could you please tell me how to solve the problem of automatic differentiation of eigenvalue decomposition in Ceres?
