### ISSUE TITLE
Some scenes will be mismatched

### ISSUE THREAD

**Issue by hunkyu** [hku-mars/BALM#6]
@Zale-Liu  : SO3::SO3(const Quaterniond&): Assertion `unit_quaternion_.squaredNorm() > SMALL_EPS' failed.
![2021-04-04 01-07-39 的屏幕截图](https://user-images.githubusercontent.com/20533364/113485870-71575280-94e2-11eb-9043-9f4a530f8821.png)
![2021-04-04 01-07-52 的屏幕截图](https://user-images.githubusercontent.com/20533364/113485871-74524300-94e2-11eb-98c6-3f8a4139f2d3.png)
Feature point extraction should be no problem, I feel that scantomap is a bit problematic

**Comment by Zale-Liu** [comment]
Yes, in this version, the scan2map module is not robust enough. You can use your own scan2map like 3.4. We will upload refined codes (Better scan2map and loop closure) in May or June.
