### ISSUE TITLE
Link for stairs bag does not work

### ISSUE THREAD

**Issue by nkhedekar** [hku-mars/BALM#7]
Really cool work! Thanks for open sourcing it! :smile: 

The [link](https://connecthkuhk-my.sharepoint.com/:u:/g/personal/u3007335_connect_hku_hk/EUauSzsnUiJCrP741WMh36kBQua3qtmNtI5FWH5HzAVkdg?e=mSRGJY) for the stairs bag listed in the Readme in [section 3.4](https://github.com/hku-mars/BALM#34-loam-as-front-end) is either inaccessible or has been moved. Can you please update it?

![image](https://user-images.githubusercontent.com/16434501/115801880-a690eb00-a392-11eb-9f5b-f5e92eaae1e6.png)

TIA!

**Comment by Camilochiang** [comment]
Up

**Comment by nkhedekar** [comment]
Thanks! The link is up but it seems the permissions still need to be corrected.
![Untitled](https://user-images.githubusercontent.com/16434501/121523818-ebcab400-c9f6-11eb-82f6-a290b1bb4d30.png)

**Comment by CanCanZeng** [comment]
I also want to test the stairs dataset, but it cannot be downloaded, can you update the download link? @Zale-Liu

**Comment by Fellowflyingsky** [comment]
> 谢谢！链接已打开，但似乎仍需要更正权限。 ![无标题](https://user-images.githubusercontent.com/16434501/121523818-ebcab400-c9f6-11eb-82f6-a290b1bb4d30.png)

你好，还能更下下楼梯的数据包么，我想测试一下

**Comment by Fellowflyingsky** [comment]
我也想测试一下stairs dataset，但是下载不了，能更新下下载链接吗？@Zale-Liu
