### ISSUE TITLE
BALM 测试结果

### ISSUE THREAD

**Issue by kxch928925819** [hku-mars/BALM#8]
BALM在检测中，多次发生imu漂移，不知道是不是imu运行太快的原因！

**Comment by Zale-Liu** [comment]
BALM暂时还没有imu，我已经适配完imu的预积分，很快就会发出来

**Comment by kxch928925819** [comment]
谢谢🙏！ 期待你们的新版本！谢谢！




------------------ 原始邮件 ------------------
发件人: Zale-Liu ***@***.***&gt;
发送时间: 2021年5月24日 23:31
收件人: hku-mars/BALM ***@***.***&gt;
抄送: Weiguo Zhao ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[hku-mars/BALM] BALM 测试结果 (#8)

**Comment by HerB1998** [comment]
请问近期有进行新版本更新的打算吗？
